from noonlight import (
    NOONLIGHT_SERVICES_FIRE,
    NOONLIGHT_SERVICES_MEDICAL,
    NOONLIGHT_SERVICES_POLICE,
)

VERSION = "v1.1.3"
DOMAIN = "noonlight"

EVENT_NOONLIGHT_TOKEN_REFRESHED = "noonlight_token_refreshed"
EVENT_NOONLIGHT_ALARM_CANCELED = "noonlight_alarm_canceled"
EVENT_NOONLIGHT_ALARM_CREATED = "noonlight_alarm_created"

NOTIFICATION_TOKEN_UPDATE_FAILURE = "noonlight_token_update_failure"
NOTIFICATION_TOKEN_UPDATE_SUCCESS = "noonlight_token_update_success"
NOTIFICATION_ALARM_CREATE_FAILURE = "noonlight_alarm_create_failure"

CONF_SECRET = "secret"
CONF_API_ENDPOINT = "api_endpoint"
CONF_TOKEN_ENDPOINT = "token_endpoint"
CONF_ADDRESS_LINE1 = "address1"
CONF_ADDRESS_LINE2 = "address2"
CONF_CITY = "city"
CONF_STATE = "state"
CONF_ZIP = "zip"

CONST_ALARM_STATUS_ACTIVE = "ACTIVE"
CONST_ALARM_STATUS_CANCELED = "CANCELED"
CONST_NOONLIGHT_HA_SERVICE_CREATE_ALARM = "create_alarm"

CONST_NOONLIGHT_SERVICE_TYPES = (
    NOONLIGHT_SERVICES_POLICE,
    NOONLIGHT_SERVICES_FIRE,
    NOONLIGHT_SERVICES_MEDICAL,
)
